src/Entity/Order.php
<?php declare(strict_types=1);

namespace App\Entity;

use App\Entity\Order\Client;
use App\Entity\Order\DeliveryType;
use App\Entity\Order\FontType;
use App\Entity\Order\PaymentType;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinColumn;
use Doctrine\ORM\Mapping\JoinTable;
use Doctrine\ORM\Mapping\OneToOne;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity()
 * @Vich\Uploadable()
 * @ORM\Table(name="order_table")
 */
class Order {
    use TimestampableEntity;

    /**
     * @var int
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer", nullable=false)
     */
    protected $id;

    /**
     * @var bool
     * @ORM\Column(type="boolean", nullable=false)
     */
    protected $processed = false;

    /**
     * @var Product[]
     * @ORM\ManyToMany(targetEntity="Product")
     * @JoinTable(name="ordered_products",
     *      joinColumns={@JoinColumn(name="order_id", referencedColumnName="id")},
     *      inverseJoinColumns={@JoinColumn(name="product_id", referencedColumnName="id")}
     *      )
     */
    protected $products;

    /**
     * @var int
     * @ORM\Column(type="integer", nullable=false)
     */
    protected $itemsCount = 1;

    /**
     * @var float
     * @ORM\Column(type="float", nullable=false)
     */
    protected $totalPrice = 0.0;

    /**
     * @ORM\Column(type="string", length=255, nullable=false)
     * @var string|null
     */
    protected $photo;

    /**
     * @var bool
     * @ORM\Column(type="boolean", nullable=false)
     */
    protected $photo3D = false;

    /**
     * @var bool
     * @ORM\Column(type="boolean", nullable=false)
     */
    protected $withText = false;

    /**
     * @var string|null
     * @ORM\Column(type="string", nullable=true)
     */
    protected $text = null;

    /**
     * @var FontType|null
     * @ORM\ManyToOne(targetEntity="App\Entity\Order\FontType")
     * @ORM\JoinColumn(name="font_id", referencedColumnName="id", nullable=true)
     */
    protected $font = null;

    /**
     * @var PaymentType
     * @ORM\ManyToOne (targetEntity="App\Entity\Order\PaymentType")
     * @ORM\JoinColumn(name="payment_id", referencedColumnName="id", nullable=false)
     */
    protected $payment;

    /**
     * @var DeliveryType
     * @ORM\ManyToOne(targetEntity="App\Entity\Order\DeliveryType")
     * @ORM\JoinColumn(name="delivery_id", referencedColumnName="id", nullable=false)
     */
    protected $delivery;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    protected $packeteryBranchName;

    /**
     * @var int|null
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $packeteryBranchId;

    /**
     * @var Client
     * @ORM\OneToOne(targetEntity="App\Entity\Order\Client", cascade={"persist", "remove"}, orphanRemoval=true)
     * @JoinColumn(name="client_id", referencedColumnName="id", nullable=false)
     */
    protected $client;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    protected $note;

    public function __construct() {
        $this->products = new ArrayCollection();
        $this->updatedAt = new DateTime();
        $this->createdAt = new DateTime();
    }

    /**
     * @return Collection
     */
    public function getProducts(): Collection {
        return $this->products;
    }

    /**
     * @param Collection $projectImages
     */
    public function setProducts(Collection $products): void {
        foreach ($products as $product) {
            $this->addProduct($product);
        }
    }

    public function addProduct(Product $product) {
        $this->products[] = $product;
        $this->updatedAt = new DateTime('now');
    }

    public function removeProduct(Product $product)
    {
        $this->products->removeElement($product);
    }

    /**
     * @return int
     */
    public function getId(): int {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId(int $id): void {
        $this->id = $id;
    }

    /**
     * @return bool
     */
    public function isProcessed(): bool {
        return $this->processed;
    }

    /**
     * @param bool $processed
     */
    public function setProcessed(bool $processed): void {
        $this->processed = $processed;
    }

    /**
     * @return float
     */
    public function getTotalPrice(): float {
        return $this->totalPrice;
    }

    /**
     * @param float $totalPrice
     */
    public function setTotalPrice(float $totalPrice): void {
        $this->totalPrice = $totalPrice;
    }

    /**
     * @return string|null
     */
    public function getPhoto(): ?string {
        return $this->photo;
    }

    /**
     * @param string|null $photo
     */
    public function setPhoto(?string $photo): void {
        $this->photo = $photo;
    }

    /**
     * @return bool
     */
    public function isPhoto3D(): bool {
        return $this->photo3D;
    }

    /**
     * @param bool $photo3D
     */
    public function setPhoto3D(bool $photo3D): void {
        $this->photo3D = $photo3D;
    }

    /**
     * @return bool
     */
    public function isWithText(): bool {
        return $this->withText;
    }

    /**
     * @param bool $withText
     */
    public function setWithText(bool $withText): void {
        $this->withText = $withText;
    }

    /**
     * @return string|null
     */
    public function getText(): ?string {
        return $this->text;
    }

    /**
     * @param string|null $text
     */
    public function setText(?string $text): void {
        $this->text = $text;
    }

    /**
     * @return FontType|null
     */
    public function getFont(): ?FontType {
        return $this->font;
    }

    /**
     * @param FontType|null $font
     */
    public function setFont(?FontType $font): void {
        $this->font = $font;
    }

    /**
     * @return PaymentType
     */
    public function getPayment(): PaymentType {
        return $this->payment;
    }

    /**
     * @param PaymentType $payment
     */
    public function setPayment(PaymentType $payment): void {
        $this->payment = $payment;
    }

    /**
     * @return DeliveryType
     */
    public function getDelivery(): DeliveryType {
        return $this->delivery;
    }

    /**
     * @param DeliveryType $delivery
     */
    public function setDelivery(DeliveryType $delivery): void {
        $this->delivery = $delivery;
    }

    /**
     * @return Client
     */
    public function getClient() {
        return $this->client;
    }

    /**
     * @param Client $client
     */
    public function setClient(Client $client): void {
        $this->client = $client;
    }

    /**
     * @return string|null
     */
    public function getNote(): ?string {
        return $this->note;
    }

    /**
     * @param string|null $note
     */
    public function setNote(?string $note): void {
        $this->note = $note;
    }

    /**
     * @return int
     */
    public function getItemsCount(): int {
        return $this->itemsCount;
    }

    /**
     * @param int $itemsCount
     */
    public function setItemsCount(int $itemsCount): void {
        $this->itemsCount = $itemsCount;
    }

    public function updateTotalPrice() {
        $price = 0;
        /** @var Product $product */
        foreach ($this->getProducts() as $product) {
            $price += $product->getDiscountPrice() ?: $product->getPrice();
            if ($this->photo3D) {
                $price += $product->getLaser3DPrice();
            }
        }

        $price = $this->itemsCount * $price;

        if ($this->getPayment()) {
            $price += $this->getPayment()->getPrice();
        }

        if ($this->getDelivery()) {
            $price += $this->getDelivery()->getPrice();
        }

        $this->totalPrice = $price;
    }

    /**
     * @return string|null
     */
    public function getPacketeryBranchName(): ?string {
        return $this->packeteryBranchName;
    }

    /**
     * @param string|null $packeteryBranchName
     */
    public function setPacketeryBranchName(?string $packeteryBranchName): void {
        $this->packeteryBranchName = $packeteryBranchName;
    }

    public function getPacketeryBranchId(): ?int {
        return $this->packeteryBranchId;
    }

    public function setPacketeryBranchId(?int $packeteryBranchId): void {
        $this->packeteryBranchId = $packeteryBranchId;
    }

    public function getPacketeryBranch(): ?string {
        $str = null;
        if ($this->packeteryBranchId) {
            $str = $this->packeteryBranchName. ' ('.$this->packeteryBranchId.')';
        }

        return $str;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-0DCY0EGGKW"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-0DCY0EGGKW');
    </script>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="/js/jquery.js"></script>
    <script src="/js/scripts.js"></script>
    <link rel="icon" href="favicon.ico" type="image/x-icon"/>
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon"/>
    <title>4EVER IN{% if title is defined %}| {{ title }}{% endif %}</title>
    <meta property="og:title" content="4EVER IN{% if title is defined %}| {{ title }}{% endif %}">
    <meta property="og:description"
          content="{% if description is defined %}| {{ description }}{% endif %}">
    <meta property="og:image" content="https://4everin.cz/images/Logo_4everin.svg">

    <meta name="twitter:title" content="{% if title is defined %}| {{ title }}{% endif %}">
    <meta name="twitter:description"
          content="{% if description is defined %}| {{ description }}{% endif %}">
    <meta name="twitter:image" content="https://4everin.cz/images/Logo_4everin.svg">
    <meta name="twitter:card" content="summary_large_image">

    <meta name="description"
          value="{% if description is defined %}| {{ description }}{% endif %}">
    <meta name="keywords" value="{% if keywords is defined %}| {{ keywords }}{% endif %}">
    {% block stylesheets %}
    {% endblock %}

    <link rel="stylesheet" href="{{ asset('css/css.css') }}">
    <link rel="stylesheet" href="{{ asset('css/alerts.css') }}">
    <!-- Facebook Pixel Code --><script>!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,document,'script','https://connect.facebook.net/en_US/fbevents.js'); fbq('init', '194000335688891'); fbq('track', 'PageView');</script><noscript> <img height="1" width="1" src="https://www.facebook.com/tr?id=194000335688891&ev=PageView&noscript=1"/></noscript><!-- End Facebook Pixel Code -->
</head>
<body>
<div class="hamburger" style="display: none">
    <img src="/images/hamburger.svg" alt="Ikona mobilního menu"/>
</div>

<div class="mobile-menu">

    <img src="/images/close_small.svg" alt="ikona zavřít" class="close" id="close-menu"/>

    <div class="content">
        <a href="{{ path('main') }}">
            <img src="/images/Logo_4everin-Logo_4everin_white.svg" alt="logo"/>
        </a>
        <div class="items">
            <a href="{{ path('eshop') }}">OBJEDNAT ONLINE</a>
            <a href="{{ path('custom') }}">SPECIFICKÁ VÝROBA</a>
            <a href="{{ path('companies') }}">VÝROBA PRO FIRMY</a>
            <a href="{{ path('photos') }}">VAŠE FOTKY 2D/3D</a>
            <a href="{{ path('reference') }}">REFERENCE</a>
            <a href="{{ path("main") }}#vyroba">VÝROBA</a>
            <a href="{{ path('contact') }}">KONTAKT</a>
        </div>
    </div>
</div>
{% block body %}{% endblock %}
{% block javascripts %}{% endblock %}
<div class="footer">
    <div class="box">
        <img src="/images/Logo_4everin.svg" alt="Logo 4everin"/>
        <div class="content">
            <div class="col col1">
                <div class="row">
                    Jsme rodinná firma na českém<br/>
                    trhu se sídlem v Pardubicích.
                </div>
                <div class="row">
                    Agentura N+N s.r.o.<br/>
                    Počaply 61<br/>
                    533 04 Sezemice<br/>
                </div>
                <div class="row">
                    IČ 26014033<br/>
                    DIČ CZ26014033<br/>
                </div>
                <div class="row gray">
                    Spisová značka C 20184/KSHK<br/>
                    Krajský soud v Hradci Králové
                </div>
            </div>
            <div class="col col2">
                <div class="title">INFORMACE</div>

                <a href="{{ path('main') }}#onas">O nás</a>
                <a href="{{ path('contact') }}">Kontakt</a>
                <a href="{{ path("photos") }}#photosDesc">Jak objednat online?</a>
                <a href="{{ path('obchodniPodminky') }}">Obchodní podmínky</a>
                <a href="{{ path('reklamace') }}">Reklamace</a>
            </div>
            <div class="col col3">
                <div class="title">VÝROBA</div>

                <a href="{{ path('custom') }}">Specifická výroba</a>
                <a href="{{ path('companies') }}">Výroba pro firmy</a>
                <a href="{{ path('photos') }}">Fotky ve skle</a>
                <a href="{{ path('eshop') }}">Objednat online</a>
            </div>
            <div class="col col4">
                <div class="title">RYCHLÝ KONTAKT</div>
                <div class="con">
                    <img src="/images/phone_black.svg"/>
                    <a href="tel:+420603524942">+420 603 524 942</a>
                </div>
                <div class="con">
                    <img src="/images/Mail_icon_black-mail_icon_black.svg"/>
                    <a href="mailto:obchod@4everin.cz">obchod@4everin.cz</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="footer-logo">
    <div class="copyright">
        © 2020, Agentura N+N s.r.o.
    </div>
    <div class="matfix-logo">
        <a href="https://www.matfix.cz" target="_blank">
            <img src="/images/matfix_paticka_new.svg" alt="Logo Matfix"><br/>
        </a>
    </div>
</div>
</body>
</html>

templates/companies.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="zakazka-page">
        <div class="main empty">
            <div class="box">
                <div class="row top">
                    <div class="left">
                        <a href="{{ path('main') }}">
                            <img src="/images/Logo_4everin-Logo_4everin_white.svg" alt="logo 4everin"/>
                        </a>
                    </div>
                    <div class="right">
                        <div class="contact">
                            <a href="tel:+420603524942">+420 603 524 942</a> | <a href="mailto:obchod@4everin.cz">obchod@4everin.cz</a>
                        </div>
                        <div class="menu">
                            <a href="{{ path('reference') }}">REFERENCE</a>
                            <a href="{{ path('main') }}#vyroba">VÝROBA</a>
                            <a href="{{ path('eshop') }}">OBJEDNAT</a>
                            <a href="{{ path('contact') }}">KONTAKT</a>
                        </div>
                    </div>
                </div>

                <div class="box-content">
                    <div class="left">
                        <div class="title">
                            Výroba pro firmy,
                            obce, kluby. Vaše
                            sdělení ve skle.
                        </div>
                        <div class="subtitle">
                            <ul>
                                <li>loga, fotky</li>
                                <li>erby, věnování</li>
                                <li>plakety, trofeje</li>
                            </ul>
                        </div>
                        <form action="{{ path('contact') }}">
                            <button type="submit" class="button-red">KONTAKTUJTE NÁS</button>
                        </form>
                    </div>
                    <div class="right">
                        <img src="/images/policie.jpg"/>
                    </div>
                </div>

            </div>
        </div>
        <div class="desc">
            <div class="box">
                <div class="left">
                    <div class="content">

                        <p>Napište nám svou představu a zeptejte se nás.
                            Vaše netradiční reklamní a dárkové předměty připravíme společně.</p>

                        <div class="quote">Pro firmy</div>
                        <ul>
                            <li>reklamní předměty</li>
                            <li>dárkové upomínky</li>
                            <li>firemní dekorace</li>
                        </ul>
                        <div class="quote">Pro města a obce</div>
                        <ul>
                            <li>reklamní upomínky</li>
                            <li>pamětní upomínky</li>
                            <li>dárkové plakety</li>
                        </ul>

                        <div class="quote">Pro sportovní kluby</div>
                        <ul>
                            <li>sportovní trofeje</li>
                            <li>sportovní plakety</li>
                            <li>fanouškovské předměty</li>
                        </ul>
                    </div>
                </div>
                <div class="right">
                    <!--<img src="publc/images/Img_o nas.jpg" width="892" height="596"/> -->
                    <img src="/images/Img_o nas.jpg"/>
                </div>
            </div>
            <div class="bottom">
                <form action="{{ path('reference') }}">
                    <button type="submit" class="button-red btn">REFERENCE</button>
                </form>
            </div>

            <div class="boxes">
                <a href="{{ path('custom') }}" class="item">
                    <div>
                        <div class="line"></div>
                        SPECIFICKÁ<br/>
                        VÝROBA
                    </div>
                </a>
                <a href="{{ path('companies') }}" class="item">
                    <div>
                        <div class="line"></div>
                        VÝROBA PRO<br/>
                        FIRMY / OBCE
                    </div>
                </a>
                <a href="{{ path('photos') }}" class="item">
                    <div>
                        <div class="line"></div>
                        VAŠE FOTKY<br/>
                        VE SKLE 2D/3D
                    </div>
                </a>
                <a href="{{ path('eshop') }}" class="item">
                    <div>
                        <div class="line"></div>
                        OBJEDNAT SVŮJ<br/>
                        DÁREK ONLINE
                    </div>
                </a>
            </div>

        </div>
    </div>
    {% block script %}
        <script>
        </script>
    {% endblock script %}
{% endblock body %}

templates/confirmation.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="text-page confirmation">
        <div class="header-box">
            <div class="logo">
                <a href="{{ path('main') }}">
                    <img src="/images/Logo_4everin-Logo_4everin_white.svg" alt="logo 4everin"/>
                </a>
            </div>
            <div class="title">
                Vaše objednávka je odeslaná
            </div>
        </div>
        <div class="content">
            <div class="text">
                <div class="title">
                    Děkujeme za Vaší objednávku
                </div>
                <p>
                    V nejbližší možné době na ni mrkneme a ozveme se Vám na Vámi uvedený e-mail nebo telefon.
                </p><br /><br />
                <p>
                    Pěkný den.
                </p>
            </div>
        </div>
    </div>
{% endblock body %}

templates/mail.html.twig
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html>
<head>
    <style>
        @import url('https://fonts.googleapis.com/css?family=Baloo|Rubik:400,500,700&display=swap');
    </style>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <meta name="x-apple-disable-message-reformatting">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="telephone=no" name="format-detection">
    <title></title>
</head>
<body style="font-family: 'Rubik', sans-serif;">
{% macro renderBool(param) %}
    {% if param  %}
        Ano
    {% else %}
        Ne
    {% endif %}
{% endmacro %}

<p>
    Dobrý den,<br><br>

    děkujeme za vyplnění objednávky.<br><br>

    O následujícím postupu Vás budeme informovat emailem či telefonicky.<br><br>

    S přáním hezkého dne 4everIn.

</p>
<div>
    <table border="0" width="800" cellpadding="0" cellspacing="0" align="left" style="padding-bottom: 30px">
        <tr>
            <td colspan="2">
                <h2>Souhrn objednávky č. {{ order.id }}</h2>
            </td>
        </tr>
        <tr>
            <td width="250">
                <table border="0" width="250" cellpadding="5" cellspacing="0" align="left">
                    <tr>
                        <td>Datum</td>
                    </tr>
                    <tr>
                        <td>Cena celkem</td>
                    </tr>
                    <tr>
                        <td>Doprava</td>
                    </tr>
                    <tr>
                        <td>Platba</td>
                    </tr>
                    <tr>
                        <td>Poznámka</td>
                    </tr>
                </table>
            </td>
            <td width="550">
                <table border="0" width="550" cellpadding="5" cellspacing="0" align="left">
                    <tr>
                        <td>{{ order.createdAt|date('d.m.Y G:i:s') }}</td>
                    </tr>
                    <tr>
                        <td>{{ order.totalPrice }} Kč</td>
                    </tr>
                    <tr>
                        <td>{{ order.delivery.name }} (+ {{ order.delivery.price }} Kč )
                            {% if order.packeteryBranchId %}
                                <br>
                                {{ order.packeteryBranch }}
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>{{ order.payment.name }} (+ {{ order.payment.price }} Kč )</td>
                    </tr>
                    <tr>
                        <td>{{ order.note }}</td>
                    </tr>
                </table>
            </td>
        </tr>

        <tr>
            <td colspan="2">
                <h2>Produkt</h2>
            </td>
        </tr>
        <tr>
            <td width="250">

                <table border="0" width="250" cellpadding="5" cellspacing="0" align="left">
                    <tr>
                        <td>Název</td>
                    </tr>
                    <tr>
                        <td>Počet kusů</td>
                    </tr>
                    <tr>
                        <td>3D</td>
                    </tr>
                    <tr>
                        <td>S textem</td>
                    </tr>
                    {% if order.withText %}
                        <tr>
                            <td>Text</td>
                        </tr>
                        <tr>
                            <td>Font</td>
                        </tr>
                    {% endif %}
                    <tr>
                        <td>Foto</td>
                    </tr>
                </table>

            </td>
            <td width="550">
                <table border="0" width="550" cellpadding="5" cellspacing="0" align="left">
                    <tr>
                        <td>{{ order.products.first.name }} {{ order.products.first.size }}</td>
                    </tr>
                    <tr>
                        <td>{{ order.itemsCount }}</td>
                    </tr>
                    <tr>
                        <td>{{ _self.renderBool(order.photo3D) }} {% if order.photo3D %} (+ {{ order.products.first.laser3DPrice }} Kč) {% endif %}</td>
                    </tr>
                    <tr>
                        <td>{{ _self.renderBool(order.withText) }}</td>
                    </tr>
                    {% if order.withText %}
                        <tr>
                            <td>{{ order.text }}</td>
                        </tr>
                        <tr>
                            <td>{{ order.font.name }}</td>
                        </tr>
                    {% endif %}
                    <tr>
                        <td><a target="_blank" href="https://4everin.cz/soubory/objednavky/{{ order.photo }}">prohlédnout</a></td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <h2>Osobní údaje</h2>
            </td>
        </tr>
        <tr>
            <td width="250">
                <table border="0" width="250" cellpadding="5" cellspacing="0" align="left">
                    <tr>
                        <td>Jméno a příjmení</td>
                    </tr>
                    <tr>
                        <td>Telefon</td>
                    </tr>
                    <tr>
                        <td>Email</td>
                    </tr>
                    {% if order.client.companyName %}
                        <tr>
                            <td>Firma</td>
                        </tr>
                        <tr>
                            <td>IČO</td>
                        </tr>
                        <tr>
                            <td>DIČ</td>
                        </tr>
                    {% endif %}
                </table>
            </td>
            <td width="550">
                <table border="0" width="550" cellpadding="5" cellspacing="0" align="left">
                    <tr>
                        <td>{{ order.client.name }}</td>
                    </tr>
                    <tr>
                        <td>{{ order.client.phone }}</td>
                    </tr>
                    <tr>
                        <td>{{ order.client.email }}</td>
                    </tr>

                    {% if order.client.companyName %}
                        <tr>
                            <td>{{ order.client.companyName }}</td>
                        </tr>
                        <tr>
                            <td>{{ order.client.ein }}</td>
                        </tr>
                        <tr>
                            <td>{{ order.client.vatNumber }}</td>
                        </tr>
                    {% endif %}

                </table>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <h2>Doručovací adresa</h2>
            </td>
        </tr>
        <tr>
            <td width="250">
                <table border="0" width="250" cellpadding="5" cellspacing="0" align="left">
                    <tr>
                        <td>Ulice a č.p.</td>
                    </tr>
                    <tr>
                        <td>Město</td>
                    </tr>
                    <tr>
                        <td>PSČ</td>
                    </tr>
                </table>
            </td>
            <td width="750">
                <table border="0" width="750" cellpadding="5" cellspacing="0" align="left">
                    <tr>
                        <td>{{ order.client.address.street }}</td>
                    </tr>
                    <tr>
                        <td>
                            {{ order.client.address.city }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            {{ order.client.address.postCode }}
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        {% if order.client.billingAddress %}
            <tr>
                <td colspan="2">
                    <h2>Fakturační adresa</h2>
                </td>
            </tr>
            <tr>
                <td width="250">
                    <table border="0" width="250" cellpadding="5" cellspacing="0" align="left">
                        <tr>
                            <td>Ulice a č.p.</td>
                        </tr>
                        <tr>
                            <td>Město</td>
                        </tr>
                        <tr>
                            <td>PSČ</td>
                        </tr>
                    </table>
                </td>
                <td width="750">
                    <table border="0" width="750" cellpadding="5" cellspacing="0" align="left">
                        <tr>
                            <td>{{ order.client.billingAddress.street }}</td>
                        </tr>
                        <tr>
                            <td>
                                {{ order.client.billingAddress.city }}
                            </td>
                        </tr>
                        <tr>
                            <td>
                                {{ order.client.billingAddress.postCode }}
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        {% endif %}

    </table>
</div>
</body>
</html>

templates/menu.html.twig
<div class="contact">
    <a href="tel:+420603524942">+420 603 524 942</a> | <a href="mailto:obchod@4everin.cz">obchod@4everin.cz</a>
</div>
<div class="menu">
    <a href="{{ path('reference') }}">REFERENCE</a>
    <a href="{{ path('main') }}#vyroba">VÝROBA</a>
    <a href="{{ path('eshop') }}">OBJEDNAT</a>
    <a href="{{ path('contact') }}">KONTAKT</a>
</div>

templates/order_complete.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<div class="contact-page">
    <div class="main empty">
        <div class="box">
            <div class="row top">
                <div class="left">
                    <a href="{{ path('main') }}">
                        <img src="/images/Logo_4everin-Logo_4everin_white.svg" alt="logo 4everin"/>
                    </a>
                </div>
                <div class="right">
                    {% include 'menu.html.twig' %}
                </div>
            </div>
            <div class="row">
                <h2>Děkujeme za objednávku, více informací naleznete ve vašem emailu.</h2>
            </div>
        </div>
    </div>
{% endblock %}